name: Build and Deploy Microservices

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Fastify Logging Service
      - name: Build and push logging-service
        uses: docker/build-push-action@v5
        with:
          context: ./fastify-logging-service
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fastify-logging-service:latest

      - name: Deploy logging-service to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
          SERVICE_ID: ${{ secrets.LOGGING_SERVICE }}
          IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/fastify-logging-service:latest
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          export RAILWAY_TOKEN=$RAILWAY_TOKEN
          railway service update --project $PROJECT_ID --service $SERVICE_ID --image $IMAGE

      # Fastify Order Service
      - name: Build and push order-service
        uses: docker/build-push-action@v5
        with:
          context: ./fastify-order-service
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fastify-order-service:latest

      - name: Deploy order-service to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
          SERVICE_ID: ${{ secrets.ORDER_SERVICE }}
          IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/fastify-order-service:latest
        run: |
          export RAILWAY_TOKEN=$RAILWAY_TOKEN
          railway service update --project $PROJECT_ID --service $SERVICE_ID --image $IMAGE

      # Fastify Product Service
      - name: Build and push product-service
        uses: docker/build-push-action@v5
        with:
          context: ./fastify-product-service
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fastify-product-service:latest

      - name: Deploy product-service to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
          SERVICE_ID: ${{ secrets.PRODUCT_SERVICE }}
          IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/fastify-product-service:latest
        run: |
          export RAILWAY_TOKEN=$RAILWAY_TOKEN
          railway service update --project $PROJECT_ID --service $SERVICE_ID --image $IMAGE

      # Fastify API Gateway
      - name: Build and push api-gateway
        uses: docker/build-push-action@v5
        with:
          context: ./fastify-api-gateway
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fastify-api-gateway:latest

      - name: Deploy api-gateway to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
          SERVICE_ID: ${{ secrets.API_GATEWAY }}
          IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/fastify-api-gateway:latest
        run: |
          export RAILWAY_TOKEN=$RAILWAY_TOKEN
          railway service update --project $PROJECT_ID --service $SERVICE_ID --image $IMAGE
