name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push fastify-logging-service
        uses: docker/build-push-action@v5
        with:
          context: ./app/fastify-logging-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/fastify-logging-service:latest

      - name: Build and push fastify-order-service
        uses: docker/build-push-action@v5
        with:
          context: ./app/fastify-order-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/fastify-order-service:latest

      - name: Build and push fastify-product-service
        uses: docker/build-push-action@v5
        with:
          context: ./app/fastify-product-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/fastify-product-service:latest

      - name: Build and push fastify-api-gateway
        uses: docker/build-push-action@v5
        with:
          context: ./app/fastify-api-gateway
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/fastify-api-gateway:latest
