name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push fastify-logging-service
        uses: docker/build-push-action@v5
        with:
          context: ./fastify-logging-service
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fastify-logging-service:latest

      - name: Build and push fastify-order-service
        uses: docker/build-push-action@v5
        with:
          context: ./fastify-order-service
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fastify-order-service:latest

      - name: Build and push fastify-product-service
        uses: docker/build-push-action@v5
        with:
          context: ./fastify-product-service
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fastify-product-service:latest

      - name: Build and push fastify-api-gateway
        uses: docker/build-push-action@v5
        with:
          context: ./fastify-api-gateway
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fastify-api-gateway:latest

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies for fastify-logging-service
        run: |
          cd fastify-logging-service
          npm install

      - name: Install dependencies for fastify-order-service
        run: |
          cd fastify-order-service
          npm install

      - name: Install dependencies for fastify-product-service
        run: |
          cd fastify-product-service
          npm install

      - name: Install dependencies for fastify-api-gateway
        run: |
          cd fastify-api-gateway
          npm install

      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          export PATH=$PATH:$HOME/.railway/bin

      - name: Log in to Railway CLI
        run: |
          echo ${{ secrets.RAILWAY_TOKEN }} | railway login --token

      - name: Link Railway project
        run: |
          railway link --project ${{
            secrets.RAILWAY_PROJECT_ID
          }}

      - name: Deploy fastify-logging-service to Railway
        run: |
          cd fastify-logging-service
          railway up --service fastify-logging-service

      - name: Deploy fastify-order-service to Railway
        run: |
          cd fastify-order-service
          railway up --service fastify-order-service

      - name: Deploy fastify-product-service to Railway
        run: |
          cd fastify-product-service
          railway up --service fastify-product-service

      - name: Deploy fastify-api-gateway to Railway
        run: |
          cd fastify-api-gateway
          railway up --service fastify-api-gateway